version: '3.8'

services:
    web:
        build:
            context: ./components/web
        command: gunicorn app:web_app --bind 0.0.0.0:5000 --worker-class aiohttp.worker.GunicornWebWorker --log-level debug --workers 3
        expose:
            - 5000
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=web_01
            
    nginx:
        build: ./components/nginx
        ports: 
            - 8080:80
        depends_on:
            - web
